#!/bin/bash
#
# Daily Scheduler - Silver Tier
# ==============================
# Runs daily at 8AM to generate summary from /Done files.
#
# Usage: ./daily_scheduler.sh
# Cron: 0 8 * * * /path/to/daily_scheduler.sh
#

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
DONE_FOLDER="$PROJECT_ROOT/Done"
LOGS_FOLDER="$PROJECT_ROOT/Logs"
DASHBOARD_FILE="$PROJECT_ROOT/Dashboard.md"
DATE=$(date +"%Y-%m-%d")
TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")

# Ensure Logs folder exists
mkdir -p "$LOGS_FOLDER"

# Output file
SUMMARY_FILE="$LOGS_FOLDER/daily_summary_$DATE.md"

echo "========================================"
echo "Daily Scheduler - Silver Tier"
echo "========================================"
echo "Date: $DATE"
echo "Time: $TIMESTAMP"
echo "Project Root: $PROJECT_ROOT"
echo "----------------------------------------"

# Check if Done folder exists
if [ ! -d "$DONE_FOLDER" ]; then
    echo "[WARNING] Done folder not found: $DONE_FOLDER"
    echo "Creating empty summary..."
    cat > "$SUMMARY_FILE" << EOF
# Daily Summary - $DATE

## Summary
No files processed today.

---
*Generated by Daily Scheduler at $TIMESTAMP*
EOF
    echo "[INFO] Empty summary created: $SUMMARY_FILE"
    exit 0
fi

# Count files in Done folder (modified today)
TODAY_FILES=$(find "$DONE_FOLDER" -type f -name "*.md" -mtime -1 2>/dev/null | wc -l)

echo "[INFO] Files completed today: $TODAY_FILES"

# Generate summary content
cat > "$SUMMARY_FILE" << EOF
# Daily Summary - $DATE

## Overview
- **Generated:** $TIMESTAMP
- **Files Completed:** $TODAY_FILES
- **Project:** $PROJECT_ROOT

## Files Processed Today

EOF

# List files completed today
if [ "$TODAY_FILES" -gt 0 ]; then
    find "$DONE_FOLDER" -type f -name "*.md" -mtime -1 -print0 2>/dev/null | \
    while IFS= read -r -d '' file; do
        filename=$(basename "$file")
        filesize=$(stat -f%z "$file" 2>/dev/null || stat -c%s "$file" 2>/dev/null || echo "unknown")
        echo "- **$filename** ($filesize bytes)" >> "$SUMMARY_FILE"
    done
    
    echo "" >> "$SUMMARY_FILE"
    
    # Extract summaries from completed files
    echo "## Content Summary" >> "$SUMMARY_FILE"
    echo "" >> "$SUMMARY_FILE"
    
    find "$DONE_FOLDER" -type f -name "*.md" -mtime -1 -print0 2>/dev/null | \
    while IFS= read -r -d '' file; do
        filename=$(basename "$file")
        echo "### $filename" >> "$SUMMARY_FILE"
        echo "" >> "$SUMMARY_FILE"
        
        # Extract first 200 chars of content (skip YAML frontmatter)
        content=$(sed -n '/^---$/,/^---$/!p' "$file" 2>/dev/null | head -c 200)
        if [ -n "$content" ]; then
            echo "$content..." >> "$SUMMARY_FILE"
        else
            echo "*No content summary available*" >> "$SUMMARY_FILE"
        fi
        echo "" >> "$SUMMARY_FILE"
        echo "---" >> "$SUMMARY_FILE"
        echo "" >> "$SUMMARY_FILE"
    done
else
    echo "*No files completed today.*" >> "$SUMMARY_FILE"
    echo "" >> "$SUMMARY_FILE"
fi

# Add statistics section
cat >> "$SUMMARY_FILE" << EOF

## Statistics

| Metric | Value |
|--------|-------|
| Total Files in Done | $(find "$DONE_FOLDER" -type f -name "*.md" 2>/dev/null | wc -l | tr -d ' ') |
| Files Today | $TODAY_FILES |
| Generated At | $TIMESTAMP |

---
*Generated by Daily Scheduler (Silver Tier)*
EOF

echo "[INFO] Summary created: $SUMMARY_FILE"

# Update Dashboard.md with latest summary info
if [ -f "$DASHBOARD_FILE" ]; then
    # Add pending approvals count if Pending_Approval folder exists
    PENDING_COUNT=0
    if [ -d "$PROJECT_ROOT/Pending_Approval" ]; then
        PENDING_COUNT=$(find "$PROJECT_ROOT/Pending_Approval" -type f -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
    fi
    
    echo "[INFO] Dashboard updated with pending count: $PENDING_COUNT"
fi

echo "----------------------------------------"
echo "[SUCCESS] Daily summary completed!"
echo "========================================"

# Output summary location
echo ""
echo "Summary saved to: $SUMMARY_FILE"
