"""
Quick Instagram Test - Create Post Request Manually
"""

import sys
from pathlib import Path
from datetime import datetime

PROJECT_ROOT = Path(__file__).parent
VAULT_PATH = PROJECT_ROOT / "Vault"
NEEDS_ACTION_PATH = VAULT_PATH / "Needs_Action"

print("=" * 60)
print("Instagram - Create Test Post Request")
print("=" * 60)

# Ensure directory exists
NEEDS_ACTION_PATH.mkdir(parents=True, exist_ok=True)

# Create test post request
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
filename = f"INSTA_POST_REQUEST_{timestamp}.md"
filepath = NEEDS_ACTION_PATH / filename

caption = """🚀 Testing my Instagram automation!

Silver Tier AI Employee is working perfectly!

💬 Tag someone who needs to see this!

#SilverTier #Automation #AI #Instagram #Testing #TechLife"""

content = f"""# Instagram Post Request

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Type:** Manual Test
**Platform:** Instagram
**Status:** Pending Approval

---

## Caption

{caption}

---

## Image

**Path:** [Add image path here or leave empty]

---

## Approval Workflow

### To Post:
1. ✅ Add image path above (optional)
2. ✅ Move this file to `Vault/Approved/`
3. ⏳ Instagram Watcher will auto-post (within 60 seconds)
4. ✅ File moves to `Vault/Done/` after posting

### To Edit:
1. ✏️ Modify caption or add image path
2. ✅ Move to `Approved/`

### To Cancel:
1. 🗑️ Delete this file

---

## Quick Commands

Move to Approved:
```bash
move "{filepath}" "Vault\\Approved\\"
```

---

*Generated by Instagram Test Script - Silver Tier AI Employee*
"""

# Write file
with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)

print()
print(f"[OK] Post request created: {filename}")
print()
print(f"Location: {filepath}")
print()
print("Next steps:")
print("1. Wait 2 minutes (auto-move to Pending_Approval/)")
print("2. Edit caption or add image path (optional)")
print("3. Move file to Vault/Approved/")
print("4. Browser will open and post to Instagram!")
print()
print("=" * 60)

# Also show file location in explorer
print(f"\nOpening folder: {NEEDS_ACTION_PATH}")
import subprocess
subprocess.run(f'explorer "{NEEDS_ACTION_PATH}"', shell=True)
