# Daily Scheduler - Silver Tier (PowerShell)
# ===========================================
# Runs daily at 8AM to generate summary from /Done files.
#
# Usage: .\daily_scheduler.ps1
# Windows Task Scheduler: Create basic task to run this script daily at 8AM
#

# Configuration
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir
$DoneFolder = Join-Path $ProjectRoot "Done"
$LogsFolder = Join-Path $ProjectRoot "Logs"
$DashboardFile = Join-Path $ProjectRoot "Dashboard.md"
$Date = Get-Date -Format "yyyy-MM-dd"
$Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

# Ensure Logs folder exists
if (-not (Test-Path $LogsFolder)) {
    New-Item -ItemType Directory -Path $LogsFolder -Force | Out-Null
}

# Output file
$SummaryFile = Join-Path $LogsFolder "daily_summary_$Date.md"

Write-Host "========================================"
Write-Host "Daily Scheduler - Silver Tier"
Write-Host "========================================"
Write-Host "Date: $Date"
Write-Host "Time: $Timestamp"
Write-Host "Project Root: $ProjectRoot"
Write-Host "----------------------------------------"

# Check if Done folder exists
if (-not (Test-Path $DoneFolder)) {
    Write-Host "[WARNING] Done folder not found: $DoneFolder"
    Write-Host "Creating empty summary..."
    
    $emptyContent = @"
# Daily Summary - $Date

## Summary
No files processed today.

---
*Generated by Daily Scheduler at $Timestamp*
"@
    
    $emptyContent | Out-File -FilePath $SummaryFile -Encoding UTF8
    Write-Host "[INFO] Empty summary created: $SummaryFile"
    exit 0
}

# Count files in Done folder (modified today)
$Today = Get-Date
$TodayFiles = Get-ChildItem -Path $DoneFolder -Filter "*.md" -File | 
    Where-Object { $_.LastWriteTime.Date -eq $Today.Date }
$TodayCount = ($TodayFiles | Measure-Object).Count

Write-Host "[INFO] Files completed today: $TodayCount"

# Generate summary content
$summaryContent = @"
# Daily Summary - $Date

## Overview
- **Generated:** $Timestamp
- **Files Completed:** $TodayCount
- **Project:** $ProjectRoot

## Files Processed Today

"@

if ($TodayCount -gt 0) {
    foreach ($file in $TodayFiles) {
        $summaryContent += "- **$($file.Name)** ($($file.Length) bytes)`n"
    }
    
    $summaryContent += "`n## Content Summary`n`n"
    
    foreach ($file in $TodayFiles) {
        $summaryContent += "### $($file.Name)`n`n"
        
        # Read file content and extract summary (skip YAML frontmatter)
        $content = Get-Content -Path $file.FullName -Raw
        # Remove YAML frontmatter
        $content = $content -replace '(?s)^---.*?---\s*', ''
        # Get first 200 characters
        if ($content.Length -gt 200) {
            $content = $content.Substring(0, 200) + "..."
        }
        $summaryContent += "$content`n`n---`n`n"
    }
} else {
    $summaryContent += "*No files completed today.*`n`n"
}

# Add statistics
$totalFiles = (Get-ChildItem -Path $DoneFolder -Filter "*.md" -File | Measure-Object).Count

$summaryContent += @"

## Statistics

| Metric | Value |
|--------|-------|
| Total Files in Done | $totalFiles |
| Files Today | $TodayCount |
| Generated At | $Timestamp |

---
*Generated by Daily Scheduler (Silver Tier)*
"@

# Write summary file
$summaryContent | Out-File -FilePath $SummaryFile -Encoding UTF8
Write-Host "[INFO] Summary created: $SummaryFile"

# Update Dashboard.md with latest summary info
if (Test-Path $DashboardFile) {
    # Add pending approvals count if Pending_Approval folder exists
    $PendingCount = 0
    $PendingFolder = Join-Path $ProjectRoot "Pending_Approval"
    if (Test-Path $PendingFolder) {
        $PendingCount = (Get-ChildItem -Path $PendingFolder -Filter "*.md" -File | Measure-Object).Count
    }
    Write-Host "[INFO] Pending approvals: $PendingCount"
}

Write-Host "----------------------------------------"
Write-Host "[SUCCESS] Daily summary completed!"
Write-Host "========================================"

# Output summary location
Write-Host ""
Write-Host "Summary saved to: $SummaryFile"
